### ISSUE TITLE
Cannot build with latest version of FsXaml (v3.1.3)

### ISSUE THREAD

**Issue by brianberns** [fsprojects/FsXaml#64]
An attempt to build an existing application that works with v.3.1.2 fails when upgraded to v.3.1.3. Using the demo application WpfMvvmAgent as an example, the compiler error messages are:

> WpfMvvmAgent\MainWindow.xaml.fs(7,23): error FS3033: The type provider 'FsXaml.XamlTypeProvider' reported an error: The type initializer for 'FsXaml.EventToMailbox' threw an exception.
 
> WpfMvvmAgent\MainWindow.xaml.fs(7,23): error FS3033: The type provider 'FsXaml.XamlTypeProvider' reported an error: The type initializer for 'FsXaml.EventToMailbox' threw an exception.
 
> WpfMvvmAgent\MainWindow.xaml.fs(11,5): error FS0945: Cannot inherit a sealed type

**Comment by ReedCopsey** [comment]
Should be fixed in 3.1.5 https://www.nuget.org/packages/FsXaml.Wpf/
